

services:
  dns:
    build: ./dns
    container_name: dns
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      rede_servidores:
        ipv4_address: 192.168.11.10

  dhcp:
    build: ./dhcp
    container_name: dhcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./dhcp/leases:/var/lib/dhcp
    networks:
      rede_clientes:
        ipv4_address: 192.168.10.10

  ubuntu-test:
    build:
      context: ./ubuntu-test
      dockerfile: Dockerfile
    container_name: ubuntu-test
    cap_add:
      - NET_ADMIN  
    networks:
      rede_clientes:
        ipv4_address: 192.168.10.50
    tty: true


  ftp:
    build: ./ftp
    container_name: ftp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "21:21"
      - "20:20"
      - "10090-10100:10090-10100"
    networks:
      rede_servidores:
        ipv4_address: 192.168.11.51

  ldap:
    build: ./ldap
    container_name: ldap
    restart: unless-stopped
    ports:
      - "389:389"
      - "636:636"
    networks:
      rede_servidores:
        ipv4_address: 192.168.11.60
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  roteador:
    build: ./router
    container_name: roteador
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      rede_servidores:
        ipv4_address: 192.168.11.254
      rede_clientes:
        ipv4_address: 192.168.10.254

  samba:
    build: ./samba
    container_name: samba
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      rede_servidores:
        ipv4_address: 192.168.11.61
    volumes:
      - ./samba/public:/samba/public

  webserver:
    build: ./webserver
    container_name: webserver
    networks:
      rede_servidores:
        ipv4_address: 192.168.11.50
    ports:
      - "8080:80"

  firewall:
    build: ./firewall
    container_name: firewall
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      rede_servidores:
        ipv4_address: 192.168.11.30
      rede_clientes:
        ipv4_address: 192.168.10.30

volumes:
  ldap_data:
  ldap_config:

networks:
  rede_servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24

  rede_clientes:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

