# Dockerfile.testes
FROM ubuntu:20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    iproute2 \
    iputils-ping \
    dnsutils \
    curl \
    netcat && \
    apt-get clean

WORKDIR /scripts
