version: '3.8'

services:
  router:
    build:
      context: ./router
    container_name: roteador
    cap_add:
      - NET_ADMIN
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.254
      rede_clientes:
        ipv4_address: 192.168.2.254
    restart: unless-stopped

  dns:
    build: ./dns
    container_name: dns
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.10
    restart: unless-stopped

  dhcp:
    build: ./dhcp
    container_name: dhcp
    cap_add:
      - NET_ADMIN
    networks:
      rede_clientes:
        ipv4_address: 192.168.2.10
    restart: unless-stopped

  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftp:/home/ftpusers
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.20
    restart: unless-stopped

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      - LDAP_ORGANISATION=Intranet
      - LDAP_DOMAIN=intranet.local
      - LDAP_ADMIN_PASSWORD=admin
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.30
    restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    command: -u "usuario;senha" -s "publico;/compartilhado;yes;no"
    volumes:
      - ./samba/compartilhado:/compartilhado
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.40
    restart: unless-stopped

  webserver:
    image: httpd:latest
    container_name: webserver
    volumes:
      - ./webserver:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.50
    restart: unless-stopped

  ubuntu-test:
    build:
      context: ./ubuntu-test
    container_name: ubuntu-test
    cap_add:
      - NET_ADMIN
    tty: true
    volumes:
      - ./scripts:/scripts
    dns:
      - 192.168.1.10
    networks:
      rede_clientes:
        ipv4_address: 192.168.2.100
    restart: unless-stopped

  testes:
    build:
      context: ./scripts
    container_name: testes
    cap_add:
      - NET_ADMIN
    tty: true
    volumes:
      - ./scripts:/scripts
      - ./logs:/resultados
    dns:
      - 192.168.1.10
    networks:
      rede_clientes:
        ipv4_address: 192.168.2.200
    restart: unless-stopped

networks:
  rede_servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

  rede_clientes:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
