version: '3.8'

services:
  router:
    image: ubuntu:20.04
    container_name: roteador
    cap_add:
      - NET_ADMIN
    command: bash /scripts/start-router.sh
    volumes:
      - ./scripts:/scripts
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.254
      rede_clientes:
        ipv4_address: 192.168.2.254

  dns:
    image: sameersbn/bind:latest
    container_name: dns
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
    volumes:
      - ./dns:/data
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.10

  dhcp:
    image: ubuntu:20.04
    container_name: dhcp
    cap_add:
      - NET_ADMIN
    command: bash /scripts/start-dhcp.sh
    volumes:
      - ./scripts:/scripts
    networks:
      rede_clientes:
        ipv4_address: 192.168.2.10

  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftp:/home/ftpusers
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.20

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      - LDAP_ORGANISATION=Intranet
      - LDAP_DOMAIN=intranet.local
      - LDAP_ADMIN_PASSWORD=admin
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.30

  samba:
    image: dperson/samba
    container_name: samba
    command: -u "usuario;senha" -s "publico;/compartilhado;yes;no"
    volumes:
      - ./samba/compartilhado:/compartilhado
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.40

  webserver:
    image: httpd:latest
    container_name: webserver
    volumes:
      - ./webserver:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.50

  ubuntu-test:
    image: ubuntu:20.04
    container_name: ubuntu-test
    cap_add:
      - NET_ADMIN
    tty: true
    volumes:
      - ./scripts:/scripts
    networks:
      rede_clientes:
        ipv4_address: 192.168.2.100

  testes:
    image: ubuntu:20.04
    container_name: testes
    command: bash -c "apt update && apt install -y iproute2 iputils-ping dnsutils curl netcat && tail -f /dev/null"
    volumes:
      - ./scripts:/scripts
    networks:
      rede_clientes:
        ipv4_address: 192.168.2.200

networks:
  rede_servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

  rede_clientes:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24

