version: "3.8"

services:

  dns:
    build: ./containers/dns
    container_name: dns_server
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.10
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  dhcp:
    build: ./containers/dhcp
    container_name: dhcp_server
    networks:
      rede_clientes:
        ipv4_address: 192.168.2.2
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  router:
    build: ./containers/router
    container_name: router
    cap_add:
      - NET_ADMIN
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.254
      rede_clientes:
        ipv4_address: 192.168.2.254
    restart: unless-stopped

  firewall:
    build: ./containers/firewall
    container_name: firewall
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.5
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    restart: unless-stopped

  ldap:
    build: ./containers/ldap
    container_name: ldap_server
    environment:
      LDAP_ORGANISATION: "Fastfood Corp"
      LDAP_DOMAIN: "fastfood.local"
      LDAP_ADMIN_PASSWORD: "admin"
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.50
    restart: unless-stopped

  samba:
    build: ./containers/samba
    container_name: samba_server
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.60
    volumes:
      - ./containers/samba/shared:/compartilhado
    depends_on:
      - ldap
    restart: unless-stopped

  ftp:
    build: ./containers/ftp
    container_name: ftp_server
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.70
    ports:
      - "21:21"
      - "20:20"
      - "10090-10100:10090-10100"
    restart: unless-stopped

  web:
    build: ./containers/webserver
    container_name: web_server
    networks:
      rede_servidores:
        ipv4_address: 192.168.1.80
    ports:
      - "8080:80"
    depends_on:
      - router
    restart: unless-stopped

  ubuntu-test:
    build: ./containers/ubuntu-test
    container_name: ubuntu_test
    cap_add:
      - NET_ADMIN
    networks:
      rede_clientes:
        ipv4_address: 192.168.2.3
      rede_servidores: {}  # Adiciona também a rede dos serviços!
    depends_on:
      - router
    restart: unless-stopped


networks:
  rede_servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

  rede_clientes:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24

