version: '3.8'

services:
  dns:
    build: ./dns
    container_name: dns
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      rede_servidores:
        ipv4_address: 172.28.0.10

  dhcp:
    build: ./dhcp
    container_name: dhcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./dhcp/leases:/var/lib/dhcp
    networks:
      rede_clientes:
        ipv4_address: 172.29.0.10

  ubuntu-test:
    build:
      context: ./ubuntu-test
      dockerfile: Dockerfile
    container_name: ubuntu-test
    cap_add:
      - NET_ADMIN
    tty: true
    dns:
      - 172.28.0.10
    networks:
      rede_clientes: {}

  ftp:
    build: ./ftp
    container_name: ftp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "21:21"
      - "20:20"
      - "10090-10100:10090-10100"
    networks:
      rede_servidores:
        ipv4_address: 172.28.0.51

  ldap:
    build: ./ldap
    container_name: ldap
    restart: unless-stopped
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      rede_servidores:
        ipv4_address: 172.28.0.60

  roteador:
    build: ./router
    container_name: roteador
    privileged: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      rede_servidores:
        ipv4_address: 172.28.0.253
      rede_clientes:
        ipv4_address: 172.29.0.253

  samba:
    build: ./samba
    container_name: samba
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./samba/public:/samba/public
    networks:
      rede_servidores:
        ipv4_address: 172.28.0.61

  webserver:
    build: ./webserver
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      rede_servidores:
        ipv4_address: 172.28.0.50

  firewall:
    build: ./firewall
    container_name: firewall
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      rede_servidores:
        ipv4_address: 172.28.0.30
      rede_clientes:
        ipv4_address: 172.29.0.30

  testes:
    build:
      context: .
      dockerfile: Dockerfile.testes
    volumes:
      - ./scripts:/scripts
    command: /bin/bash /scripts/testes.sh

volumes:
  ldap_data:
  ldap_config:

networks:
  rede_servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.254

  rede_clientes:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
          gateway: 172.29.0.254

